### PR TITLE
Check if Labels are set and fix getLabel in all resources using labels

### LINKED ISSUE #427: [ERROR] setting state: labels: '': source data must be an array or slice, got struct
When turning TF debug logs (`export TF_LOG="DEBUG"`), I found this following error which make it sounds like there is something wrong with the `getLabels()`.

```
packetfabric_cloud_router_connection_google.crc_2: Refreshing state... [id=PF-L3-CON-3277628]
2023-04-11T18:38:08.908Z [INFO]  provider.terraform-provider-packetfabric: 2023/04/11 18:38:08 [ERROR] setting state: labels: '': source data must be an array or slice, got struct: timestamp=2023-04-11T18:38:08.908Z
```

### PR DESCRIPTION
**Pull request by rjouhann**
## Description

Check if Labels are set and fix getLabel in all resources using labels.

Closes #427 

## Checklist

- [x] tested locally

### CODE REVIEW

**Review by medzin — APPROVED** [review]

**Review by medzin — APPROVED** [review]

**Review by solababs — APPROVED** [review]

File: internal/provider/labels_common.go [hunk 1]
```diff
@@ -31,10 +31,10 @@ func updateLabels(c *packetfabric.PFClient, circuitId string, labels interface{}
...
 }
 
-func getLabels(c *packetfabric.PFClient, circuitId string) (*packetfabric.LabelsResponse, error) {
+func getLabels(c *packetfabric.PFClient, circuitId string) ([]string, error) {
 	resp, err := c.GetLabels(circuitId)
 	if err != nil {
 		return nil, err
 	}
-	return resp, nil
+	return resp.Labels, nil
```
Comment (solababs) [inline internal/provider/labels_common.go:39]: Good catch
